import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } from 'docx';
import { TranscriptSegment } from '@/lib/supabase/types';

interface DocxOptions {
  title: string;
  content: string;
  segments?: TranscriptSegment[];
  includeTimestamps?: boolean;
  language?: string;
  duration?: number;
  createdAt?: string;
}

/**
 * Generate a DOCX document from a transcript in memory, return as Buffer.
 */
export async function generateDocx({ title, content, segments, includeTimestamps = true, language, duration, createdAt }: DocxOptions): Promise<Uint8Array> {
  const paragraphs: Paragraph[] = [];

  // Title
  paragraphs.push(
    new Paragraph({
      text: title,
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 200 },
    })
  );

  // Metadata row
  const metaParts: string[] = [];
  if (language) metaParts.push(`Language: ${language.toUpperCase()}`);
  if (duration) {
    const mins = Math.floor(duration / 60);
    const secs = Math.round(duration % 60);
    metaParts.push(`Duration: ${mins}m ${secs}s`);
  }
  if (createdAt) metaParts.push(`Created: ${new Date(createdAt).toLocaleDateString()}`);
  metaParts.push('Generated by theandscribe');

  if (metaParts.length > 0) {
    paragraphs.push(
      new Paragraph({
        children: [new TextRun({ text: metaParts.join('   |   '), color: '888888', size: 18 })],
        spacing: { after: 300 },
      })
    );
  }

  // Body content
  if (includeTimestamps && segments && segments.length > 0) {
    for (const seg of segments) {
      const mins = Math.floor(seg.start / 60);
      const secs = Math.floor(seg.start % 60);
      const timeStr = `[${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')}]`;

      paragraphs.push(
        new Paragraph({
          children: [
            new TextRun({ text: timeStr + ' ', color: 'F5C518', bold: true, size: 20 }),
            new TextRun({ text: seg.text.trim(), size: 22 }),
          ],
          spacing: { after: 120 },
        })
      );
    }
  } else {
    // Split plain text into paragraphs
    const parts = content.split('\n\n').filter(Boolean);
    for (const part of parts) {
      paragraphs.push(
        new Paragraph({
          children: [new TextRun({ text: part.trim(), size: 22 })],
          spacing: { after: 200 },
        })
      );
    }
  }

  const doc = new Document({
    sections: [{ children: paragraphs }],
    title,
    description: 'Generated by theandscribe',
  });

  const buffer = await Packer.toBuffer(doc);
  return new Uint8Array(buffer);
}
