import { jsPDF } from 'jspdf';
import { TranscriptSegment } from '@/lib/supabase/types';
import { formatSegments } from '@/lib/transcription/helpers';

interface PdfOptions {
  title: string;
  content: string;
  segments?: TranscriptSegment[];
  includeTimestamps?: boolean;
  language?: string;
  duration?: number;
  createdAt?: string;
}

/**
 * Generate a PDF from a transcript in memory, return as Buffer.
 * Uses jsPDF — no file system access.
 */
export function generatePdf({ title, content, segments, includeTimestamps = true, language, duration, createdAt }: PdfOptions): Uint8Array {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  let y = margin;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(30, 30, 30);
  const titleLines = doc.splitTextToSize(title, contentWidth);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 10 + 4;

  // Divider
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 6;

  // Metadata
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);

  const meta: string[] = [];
  if (language) meta.push(`Language: ${language.toUpperCase()}`);
  if (duration) {
    const mins = Math.floor(duration / 60);
    const secs = Math.round(duration % 60);
    meta.push(`Duration: ${mins}m ${secs}s`);
  }
  if (createdAt) meta.push(`Created: ${new Date(createdAt).toLocaleDateString()}`);
  meta.push('Generated by theandscribe');

  doc.text(meta.join('   |   '), margin, y);
  y += 10;

  // Body text
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(40, 40, 40);

  const bodyText = includeTimestamps && segments && segments.length > 0
    ? formatSegments(segments)
    : content;

  const bodyLines = doc.splitTextToSize(bodyText, contentWidth);

  for (const line of bodyLines) {
    if (y > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
    doc.text(line, margin, y);
    y += 6;
  }

  // Return as Node.js Buffer
  const output = doc.output('arraybuffer');
  return new Uint8Array(output);
}
